name: nastya_diplom
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.0.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  audioplayers: ^4.1.0
  path_provider: ^2.1.1



dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/background/sound1.mp3
    - assets/sounds/background/sound2.mp3
    - assets/sounds/background/sound3.mp3
    - assets/sounds/background/sound4.mp3
    - assets/sounds/background/sound5.mp3

    - assets/sounds/events/sound1.mp3
    - assets/sounds/events/sound2.wav
    - assets/sounds/events/sound3.wav
    - assets/sounds/events/sound4.wav
    - assets/sounds/events/sound5.mp3
    - assets/sounds/events/sound6.wav